---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore

  - package-ecosystem: "gomod"
    directories:
      - "examples/auth-nkeys-stream"
      - "examples/auth-none-kv"
      - "examples/auth-none-stream"
      - "examples/auth-user-pass-stream"
      - "examples/workqueue-stream"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
